### ISSUE TITLE
Cases not handled well

### ISSUE THREAD

**Issue by einhverfr** [adjust/kafka_fdw#6]
In my input handling branch I have been able to cause certain misbehaviours on bad inputs into Kafka.

So far there are no segmentation faults or similar errors, but these could still cause serious issues reading the Kafka data.  The major difficulties have to do with handling bad representations of expected data types.

So for example if there is an integer field in the foreign table based on csv and I write a record to Kafka with that field set to a value of "foo" or "100000000000" I will get an error such as "Integer out of range" or "Invalid representation of integer."

This means that we have an important case we have to address, which is what happens when the data is actually unexpected or bad in Kafka.  Do we skip over those records?  Do we ignore the problem and assume we fix it on the Kafka side?  Do we do something else?

For test cases you can insert into the Kafka queue CSV examples like:
```
100000000000,100000000000,1000000000,1000000000
"Test", 123, 122.22
"Test, the game", 1222, 122,22
122,22
Foo,Bar,Baz,123
{"foo" 123, "Bar": 134}
```

**Comment by rapimo** [comment]
done by e2856312c1a99ea2dff7ccf665443eb349c46c86
